-- MySQL Script generated by MySQL Workbench
-- Wed Feb  4 22:17:24 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema construhogar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `construhogar` ;

-- -----------------------------------------------------
-- Schema construhogar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `construhogar` DEFAULT CHARACTER SET utf8mb3 ;
USE `construhogar` ;

-- -----------------------------------------------------
-- Table `construhogar`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construhogar`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `tipo_documento` VARCHAR(80) NULL DEFAULT NULL,
  `numero_documento` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `correo` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `correo_UNIQUE_cli` ON `construhogar`.`cliente` (`correo` ASC) VISIBLE;

CREATE UNIQUE INDEX `unique_documento_cli` ON `construhogar`.`cliente` (`numero_documento` ASC, `tipo_documento` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `construhogar`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construhogar`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `tipo_documento_emp` VARCHAR(45) NULL DEFAULT NULL,
  `numero_documento_emp` VARCHAR(20) NULL DEFAULT NULL,
  `correo_emp` VARCHAR(80) NULL DEFAULT NULL,
  `direccion_emp` VARCHAR(100) NULL DEFAULT NULL,
  `cargo` VARCHAR(50) NULL DEFAULT NULL,
  `salario` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `correo_emp_UNIQUE` ON `construhogar`.`empleado` (`correo_emp` ASC) VISIBLE;

CREATE INDEX `unique_documento_emp` ON `construhogar`.`empleado` (`tipo_documento_emp` ASC, `numero_documento_emp` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `construhogar`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construhogar`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(45) NULL DEFAULT NULL,
  `numero_documento_prov` VARCHAR(45) NOT NULL,
  `contacto` VARCHAR(80) NULL DEFAULT NULL,
  `direccion` VARCHAR(120) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `unique_documento_prov` ON `construhogar`.`proveedor` (`numero_documento_prov` ASC, `tipo_documento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `construhogar`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construhogar`.`compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `id_proveedor` INT NULL DEFAULT NULL,
  `id_empleado` INT NULL DEFAULT NULL,
  `fecha_compra` DATE NOT NULL,
  PRIMARY KEY (`id_compra`),
  CONSTRAINT `fk_compra_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `construhogar`.`empleado` (`id_empleado`),
  CONSTRAINT `fk_compra_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `construhogar`.`proveedor` (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `id_proveedor_idx` ON `construhogar`.`compra` (`id_proveedor` ASC) VISIBLE;

CREATE INDEX `fk_compra_empleado` ON `construhogar`.`compra` (`id_empleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `construhogar`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construhogar`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NULL DEFAULT NULL,
  `categoria` VARCHAR(50) NULL DEFAULT NULL,
  `id_proveedor` INT NULL DEFAULT NULL,
  `marca` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`),
  CONSTRAINT `id_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `construhogar`.`proveedor` (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `id_proveedor_idx` ON `construhogar`.`producto` (`id_proveedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `construhogar`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construhogar`.`detalle_compra` (
  `id_detalle_compra` INT NOT NULL AUTO_INCREMENT,
  `id_compra` INT NULL DEFAULT NULL,
  `id_producto` INT NULL DEFAULT NULL,
  `cantidad_compra` INT NULL DEFAULT NULL,
  `costo_unitario` DECIMAL(10,2) NULL DEFAULT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_detalle_compra`),
  CONSTRAINT `fk_detalle_compra_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `construhogar`.`producto` (`id_producto`),
  CONSTRAINT `id_compra`
    FOREIGN KEY (`id_compra`)
    REFERENCES `construhogar`.`compra` (`id_compra`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `id_compra_idx` ON `construhogar`.`detalle_compra` (`id_compra` ASC) VISIBLE;

CREATE INDEX `id_producto_idx` ON `construhogar`.`detalle_compra` (`id_producto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `construhogar`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construhogar`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `estado` VARCHAR(30) NULL DEFAULT NULL,
  `id_cliente` INT NULL DEFAULT NULL,
  `id_empleado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_pedido`),
  CONSTRAINT `FKqbl4adl78gxdv0wbx3nq03awv`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `construhogar`.`empleado` (`id_empleado`),
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `construhogar`.`cliente` (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `id_cliente_idx` ON `construhogar`.`pedido` (`id_cliente` ASC) VISIBLE;

CREATE INDEX `FKqbl4adl78gxdv0wbx3nq03awv` ON `construhogar`.`pedido` (`id_empleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `construhogar`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construhogar`.`detalle_pedido` (
  `id_detalle_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NULL DEFAULT NULL,
  `id_producto` INT NULL DEFAULT NULL,
  `cantidad_pedido` INT NULL DEFAULT NULL,
  `precio_unitario_vent` DECIMAL(10,2) NULL DEFAULT NULL,
  `subtotal` DECIMAL(10,2) NULL DEFAULT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_detalle_pedido`),
  CONSTRAINT `fk_detalle_pedido_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `construhogar`.`producto` (`id_producto`),
  CONSTRAINT `id_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `construhogar`.`pedido` (`id_pedido`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `id_pedido_idx` ON `construhogar`.`detalle_pedido` (`id_pedido` ASC) VISIBLE;

CREATE INDEX `id_producto_idx` ON `construhogar`.`detalle_pedido` (`id_producto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `construhogar`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construhogar`.`factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `id_pedido` INT NULL DEFAULT NULL,
  `id_cliente` INT NULL DEFAULT NULL,
  `id_empleado` INT NULL DEFAULT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `medio_pago` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_factura`),
  CONSTRAINT `id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `construhogar`.`empleado` (`id_empleado`),
  CONSTRAINT `id_factura_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `construhogar`.`cliente` (`id_cliente`),
  CONSTRAINT `id_factura_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `construhogar`.`pedido` (`id_pedido`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `id_pedido_idx` ON `construhogar`.`factura` (`id_pedido` ASC) VISIBLE;

CREATE INDEX `id_cliente_idx` ON `construhogar`.`factura` (`id_cliente` ASC) VISIBLE;

CREATE INDEX `id_empleado_idx` ON `construhogar`.`factura` (`id_empleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `construhogar`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construhogar`.`inventario` (
  `id_inventario` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NULL DEFAULT NULL,
  `stock_actual` INT NULL DEFAULT NULL,
  `ubicacion` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_inventario`),
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `construhogar`.`producto` (`id_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `id_producto_UNIQUE` ON `construhogar`.`inventario` (`id_producto` ASC) VISIBLE;

CREATE UNIQUE INDEX `UKtlye33nglhh35y08rxqrumnfw` ON `construhogar`.`inventario` (`id_producto` ASC) VISIBLE;

CREATE INDEX `id_ubicacion_pro` ON `construhogar`.`inventario` (`id_producto` ASC, `ubicacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `construhogar`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `construhogar`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(80) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_usuario_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `construhogar`.`empleado` (`id_empleado`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `correo_UNIQUE` ON `construhogar`.`usuario` (`correo` ASC) VISIBLE;

CREATE INDEX `fk_usuario_empleado` ON `construhogar`.`usuario` (`id_empleado` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
